apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: challenge-flutter-go
spec:
  selector:
    app: challenge-flutter-go-backend-deployment
  ports:
  - port: 8080

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: challenge-flutter-go-backend-pv
  namespace: challenge-flutter-go
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/challenge-flutter-go-backend-pv/uploads"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: challenge-flutter-go-backend-pvc
  namespace: challenge-flutter-go
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-flutter-go-backend-deployment
  namespace: challenge-flutter-go
spec:
  selector:
    matchLabels:
      app: challenge-flutter-go-backend-deployment
  template:
    metadata:
      labels:
        app: challenge-flutter-go-backend-deployment
    spec:
      volumes:
      - name: challenge-flutter-go-backend-pv
        persistentVolumeClaim:
          claimName: challenge-flutter-go-backend-pvc
      containers:
      - name: challenge-flutter-go-backend-deployment
        image: gatien1/challenge-flutter-go-backend:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 45
          periodSeconds: 1
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: challenge-flutter-go-config
              key: backend_port
        - name: MODE
          valueFrom:
            configMapKeyRef:
              name: challenge-flutter-go-config
              key: mode
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: challenge-flutter-go-config
              key: database_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: challenge-flutter-go-config
              key: database_port
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: challenge-flutter-go-config
              key: database_user
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: challenge-flutter-go-config
              key: database_name
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database_password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt_secret

        ports:
        - containerPort: 8080
        volumeMounts:
        - name: challenge-flutter-go-backend-pv
          mountPath: /app/uploads
