basePath: /
definitions:
  requests.AuthLoginBody:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  requests.TripAddTransportBody:
    properties:
      EndAddress:
        type: string
      EndDate:
        type: string
      StartAddress:
        type: string
      StartDate:
        type: string
      TransportType:
        type: string
    required:
    - EndAddress
    - EndDate
    - StartAddress
    - StartDate
    - TransportType
    type: object
  requests.TripCreateBody:
    properties:
      city:
        type: string
      country:
        type: string
      endDate:
        type: string
      name:
        type: string
      startDate:
        type: string
    required:
    - city
    - country
    - endDate
    - name
    - startDate
    type: object
  requests.UserCreateBody:
    properties:
      password:
        maxLength: 64
        minLength: 8
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  responses.LoginResponse:
    properties:
      token:
        type: string
    type: object
  responses.TripAddTransport:
    properties:
      endAddress:
        type: string
      endDate:
        type: string
      startAddress:
        type: string
      startDate:
        type: string
      transportType:
        type: string
      trip:
        $ref: '#/definitions/responses.TripResponse'
      tripId:
        type: integer
    type: object
  responses.TripResponse:
    properties:
      city:
        type: string
      country:
        type: string
      endDate:
        type: string
      id:
        type: integer
      name:
        type: string
      owner:
        $ref: '#/definitions/responses.UserResponse'
      participants:
        items:
          $ref: '#/definitions/responses.UserResponse'
        type: array
      startDate:
        type: string
    type: object
  responses.UserInfoResponse:
    properties:
      id:
        type: integer
      role:
        type: string
      trips:
        items:
          $ref: '#/definitions/responses.TripResponse'
        type: array
      username:
        type: string
    type: object
  responses.UserResponse:
    properties:
      id:
        type: integer
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Challenge Flutter Go
    url: https://challenge-flutter-go.com
  description: This is the API for the Challenge Flutter Go project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://challenge-flutter-go.com/terms
  title: Challenge Flutter Go API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login the user
      parameters:
      - description: Body of the request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.AuthLoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.LoginResponse'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
      summary: Login the user
      tags:
      - auth
  /trips:
    get:
      consumes:
      - application/json
      description: Get all trips associated with the current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.TripResponse'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
      security:
      - BearerAuth: []
      summary: Get all trips
      tags:
      - trips
    post:
      consumes:
      - application/json
      description: Create a new trip & associate it with the current user
      parameters:
      - description: Body of the trip
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.TripCreateBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.TripResponse'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
      security:
      - BearerAuth: []
      summary: Create a new trip
      tags:
      - trips
  /trips/{id}:
    get:
      consumes:
      - application/json
      description: Get a trip by its id
      parameters:
      - description: ID of the trip
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.TripResponse'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "404":
          description: Not Found
          schema: {}
      security:
      - BearerAuth: []
      summary: Get a trip
      tags:
      - trips
  /trips/{id}/transports:
    post:
      consumes:
      - application/json
      description: Add a transport to a trip
      parameters:
      - description: ID of the trip
        in: path
        name: id
        required: true
        type: string
      - description: Body of the transport
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.TripAddTransportBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.TripAddTransport'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
      security:
      - BearerAuth: []
      summary: Add a transport
      tags:
      - trips
  /trips/{id}/transports/{transportID}:
    delete:
      consumes:
      - application/json
      description: Delete a transport from a trip
      parameters:
      - description: ID of the trip
        in: path
        name: id
        required: true
        type: string
      - description: ID of the transport
        in: path
        name: transportID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema: {}
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "404":
          description: Not Found
          schema: {}
      security:
      - BearerAuth: []
      summary: Delete a transport
      tags:
      - trips
  /trips/join/{id}:
    post:
      consumes:
      - application/json
      description: Join an existing trip using its inviteCode and associate it with
        the current user
      parameters:
      - description: Invite code of the trip
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.TripResponse'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
      security:
      - BearerAuth: []
      summary: Join a trip
      tags:
      - trips
  /users:
    post:
      consumes:
      - application/json
      description: Register a new user with a username and a password
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.UserCreateBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.UserInfoResponse'
        "400":
          description: Bad Request
          schema: {}
      summary: Register a new user
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get the user by his id
      parameters:
      - description: ID of the user
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserInfoResponse'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "404":
          description: Not Found
          schema: {}
      security:
      - BearerAuth: []
      summary: Get the user
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
