name: Release Flutter App
run-name: ${{ github.actor }} release a new version (${{ github.sha }})

concurrency: flutter-release

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'move_together_app/**'
      - '.github/workflows/flutter_release.yaml'

defaults:
  run:
    working-directory: move_together_app

jobs:
  buildandroid:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Copy .env file
      run: cp .env.release .env
    - name: Retrive dependencies
      run: flutter pub get
    - name: Build Android
      run: flutter build apk --release
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: move_together_app/build/app/outputs/flutter-apk/app-release.apk

  releaseNewVersion:
    name: Release new version
    runs-on: ubuntu-latest
    needs: buildandroid
    steps:
    - uses: actions/checkout@v4
    - name: Retrieve APK
      uses: actions/download-artifact@v4
      with:
        name: app-release.apk
        path: move_together_app/build/app/outputs/flutter-apk/app-release.apk
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: move_together_app/build/app/outputs/flutter-apk/app-release.apk
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ github.run_number }}
        fail_on_unmatched_files: true
        make_latest: true
