name: Go

on:

  push:
    branches: [ "main" ]
    paths: 
      - 'go/**'
      - '.github/workflows/go.yaml'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'go/**'
      - '.github/workflows/go.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go/go.mod'

    - name: Install depencies
      working-directory: go
      run: go mod download

    - name: Build
      working-directory: go
      run: go build -v main.go

    # - name: Test
    #   run: go test -v ./...
